""" Pipeline for calling SNPs, subsampling, and preparing scripts for running Structure on the DLX cluster. """
# TODO: rule for removing bad loci
# TODO: rule "report" for summarizing matrix
import Bio.SeqIO
import collections
import datetime
import os
import plotly
import time

# TODO: report snps per locus histogram
configfile: "config.yaml"
haplotypes_dir = config['haplotypes_dir']

rule all:
    input:
        expand("snp_sites/{locus}.fna", locus=loci)

rule snp_sites:
    input:
        "{haplotypes_dir}/{{locus}}.fna".format(haplotypes_dir=haplotypes_dir)
    output:
        "snp_sites/{locus}.fna"
    log:
        "logs/snp_sites/{locus}.log"
    benchmark:
        "benchmarks/snp_sites/{locus}.txt"
    shell:
        "snp-sites -o {output} {input} 2> {log}"

rule snp_subsample:
    input:
        expand("snp_sites/{locus}.fna", locus=loci)
    output:
        expand("snp_subsamples/{subsample_base}{num}.{{ext}}", subsample_base=config["snp_subsample"]["output_filename_base"], num=range(config["snp_subsample"]["num_subsamples"])),
        "snp_subsample/all-snps-all-loci.{ext}"
    params:
        fn_base = config["snp_subsample"]["output_filename_base"],
        num_subsamples = config["snp_subsample"]["num_subsamples"],
        output_format = config["snp_subsample"]["output_format"]
    shell:
        "scripts/snp_subsample.py snp_sites/ snp_subsamples/{params.fn_base} --all-snps-all-loci "
        "--output-format {params.output_format} --num_subsamples {params.num_subsamples}"

rule write_strx_scripts:
    input:
        "snp_subsamples/{subsample_filename}.{ext}"
    output:
        expand("structure/strx_{{subsample_filename}}_{k}.sh", k=range(config["structure"]["k_min"], config["structure"]["k_max"] + 1))
    params:
        strx_path = config["structure"]["path"],
        num_runs = config["structure"]["num_runs"],
        k_min = config["structure"]["k_min"],
        k_max = config["structure"]["k_max"],
        email = config["structure"]["email"]
    run:
        N = 0  # individuals
        L = 0  # loci
        with open(input[0], 'r') as file:
            is_first = True
            for line in file:
                N += 1
                if is_first:
                    is_first = False
                    L = len(line.split()) - 1
        N = N / 2
        for k in range(params.k_min, params.k_max + 1):
            script = "#!/bin/bash\n#SBATCH --mail-type=ALL\n#SBATCH --mail-user={email}\nSBATCH_NODELIST: $SBATCH_NODELIST\n\n".format(email=params.email)
            for run in range(1, params.num_runs + 1):
                script += "{strx_path} -i {subsample} -K {k} -L {L} -N {N} -o {{subsample_filename}}_k{k}_run{run}.out &\nsleep 10\n\n".format(strx_path=params.strx_path, subsample=input[0], k=k, L=L, N=N, run=run)
            script += 'wait'
            with open('structure/strx_{{subsample}}_k{k}.sh'.format(k=k), 'w') as script_file:
                script_file.write(script)
