""" Pipeline for calling haplotypes on Illumina sequences and combining with haplotypes from 454 data. """
# TODO: rule for removing bad loci
# TODO: rule "report" for summarizing matrix
import Bio.SeqIO
import collections
import datetime
import os
import plotly
import time

configfile: "config.yaml"
reference_file = config["reference"]
reference_sequences = {seq_record.id: seq_record for seq_record in Bio.SeqIO.parse(reference_file, 'fasta')}

loci_all=set(reference_sequences.keys())
loci_454 = {fn.strip(".fna") for fn in os.listdir(config["454_haplotypes_dir"])}
loci_bad = set(config["bad_loci"])
loci_bad.update(loci_all - loci_454)
loci = loci_all - loci_bad

pair1, pair2 = "R1", "R2"
hap_numbers = ["1", "2"]

include: "rules/haplotype_illumina_data.smk"
include: "rules/align_454_haplotypes.smk"

rule all:
    input:
        config["matrix_filename"]

rule combine_454_and_illumina:
    input:
        haps_454="intermediates_454/haps_aligned_filtered/{locus}.fna",
        haps_illumina="intermediates_illumina/haplotypes/{locus}.fna"
    output:
        protected("haplotypes/{locus}.fna")
    shell:
        "cat {input} > {output}"

rule remove_bad_loci:
    input:
        expand("haplotypes/{locus}.fna", locus=loci)
    output:
        "logs/removed_bad_loci.txt"
    run:
        removed_loci = list()
        for fn in input:
            locus = fn.split('/')[1].split('.')[0]
            if locus in bad_loci:
                os.remove(fn)
                removed_loci.append(locus)
        with open(output[0], 'w') as file:
            file.write('\n'.join(removed_loci))

rule build_matrix:
    input:
        expand("haplotypes/{locus}.fna", locus=loci)
    output:
        matrix=config["matrix_filename"],
        histogram=config["hist_filename"]
    benchmark:
        "benchmarks/build_matrix.txt"
    run:
        individuals_to_seq_runs = collections.defaultdict(set)
        for working_dir, subdirs, files in os.walk(os.path.expanduser(config['illumina_fastq_dir'])):
            for filename in files:
                if filename[:4] != "Icon":
                    indiv_id = filename.split('_')[0]
                    base, subdir = os.path.split(working_dir)
                    individuals_to_seq_runs[indiv_id].add(subdir)
        for filename in os.listdir(config["454_haplotypes_dir"]):
            with open(os.path.join(config["454_haplotypes_dir"], filename), 'r') as infile:
                for seq_record in Bio.SeqIO.parse(infile, 'fasta'):
                    individuals_to_seq_runs[seq_record.id].add("454")
        matrix = "individual_id\tsequencing_runs"
        input = sorted(input)
        loci = [filename.split('/')[-1].split('.fna')[0] for filename in input]
        individuals_to_loci = collections.defaultdict(set)
        for locus_filename in input:
            locus_id = locus_filename.split('/')[-1].split('.fna')[0]
            matrix += "\t" + locus_id
            with open(locus_filename, 'r') as file:
                for line in file:
                    if line[0] == '>':
                        indiv_id = line[1:].split('_')[0]
                        individuals_to_loci[indiv_id].add(locus_id)
        for indiv_id in sorted(individuals_to_loci):
            matrix += '\n' + indiv_id + '\t' + ', '.join(sorted(individuals_to_seq_runs[indiv_id]))
            for locus_id in loci:
                matrix += '\t1' if locus_id in individuals_to_loci[indiv_id] else '\t0'
        with open(output.matrix, 'w') as file:
            file.write(matrix)
        plotly.offline.plot(plotly.graph_objs.Figure(data=[plotly.graph_objs.Histogram(x=len(individuals_in_loci[indiv_id]), name=indiv_id, opacity=0.75, autobinx=True) for indiv_id in sorted(individuals_in_loci)],
                            layout=plotly.graph_objs.Layout(barmode='overlay', title=('Individuals in Loci'), xaxis=dict(title='Number of Loci'), yaxis=dict(title='Number of Individuals'))),
                            filename=output.histogram, auto_open=True)
rule report:
    input:
        matrix=config["matrix_filename"],
        hist=config["hist_filename"],
        removed_loci_file="logs/removed_bad_loci.txt"
    output:  # TODO: histogram showing number of individuals per locus
        "reports/report.html"
    run:
        from snakemake.utils import report
        with open(input.matrix) as file:
            matrix = file.readlines()
        num_individuals = len(matrix) - 1
        num_loci = len(loci)
        with open(input.removed_bad_loci, 'r') as file:
            removed_loci = file.readlines()
        report("""
        Haplotyping pipeline for the Tiger Salamander Project
        ===================================

        {num_individuals} individuals were haplotyped for {num_loci} loci (see Table T1_ and Graph G1_).
        Loci removed: {removed_loci}
        """, output[0], T1=input.matrix, G1=input.hist)
