reference: reference/ambystoma_reference.fna
illumina_fastq_dir: data/illumina_test
454_haplotypes_dir: data/454_test
matrix_filename: matrix_testdata.tsv
trimmomatic_adapter: adapters/TruSeq3-PE.fa
bad_loci:
  - E12G1
  - E6A11
  - E7G8
