reference: ../reference/ambystoma_reference.fna
illumina_fastq_dir: data/illumina_fastq
454_haplotypes_dir: data/454_haplotypes
trimmomatic_adapter: adapters/TruSeq3-PE.fa
bad_loci:
  - E12G1
  - E6A11
  - E7G8
bad_individuals:
  - 3233
  - 2561
snp_subsample:
    output_filename_base: snp_sub_
    num_subsamples: 10
    output_format: strx
subsets:
    all:
        - 1228
        - 1230
        - 1267
        - 1269
    group1:
        - 1228
        - 1230
    group2:
        - 1267
        - 1269
structure:
    path: /home/klso224/tools/structure-2.3.4/structure
    num_runs: 16  # number of threads available
    k_min: 2
    k_max: 8
    email: kellysovacool@uky.edu
