channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - trung
dependencies:
  - bcftools=1.3.1
  - biopython=1.70
  - bwa=0.7.12
  - docopt=0.6.2
  - docutils=0.14
  - freebayes=1.1.0
  - graphviz=2.38.0
  - numpy=1.14.2
  - openjdk=8.0.121
  - plotly=2.5.1
  - python=3.5.1
  - pyvcf=0.6.8
  - pyyaml=3.11
  - samtools=1.3.1
  - snakemake=3.11.0
  - snp-sites=2.3.3
  - trimmomatic=0.36
  - vcftools=0.1.15
  - whatshap=0.13
  - xhtml2pdf
