reference: ../reference/ambystoma_reference.fna
illumina_fastq_dir: data/illumina_fastq
454_haplotypes_dir: data/454_haplotypes
trimmomatic_adapter: adapters/TruSeq3-PE.fa
bad_loci:
  - E12G1
  - E6A11
  - E7G8
snp_subsample:
    output_filename_base: snp_sub_
    num_subsamples: 1
    output_format: strx
structure:
    path: /home/klso224/tools/structure-2.3.4/structure
    num_runs: 16  # number of threads available
    k_min: 2
    k_max: 8
    email: kellysovacool@uky.edu
read_count_threshold: 30
loci_missing_threshold: 0.5